[tool.briefcase]
project_name = "Podcaster"
bundle = "cz.vgg"
version = "0.0.1"
url = "https://vgg.cz/podcaster"
license = "MIT license"
author = '@vvveracruz'
author_email = "me@vgg.cz"

[tool.briefcase.app.podcaster]
formal_name = "Podcaster"
description = "The queuer of dreams."
icon = "src/podcaster/resources/podcaster"
sources = ['src/podcaster']
requires = [
    "feedparser", 
    "requests", 
    "pygame"
]


[tool.briefcase.app.podcaster.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.podcaster.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.podcaster.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.podcaster.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.podcaster.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.podcaster.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.podcaster.android]
requires = [
    'toga-android>=0.3.0.dev35'
]
